import React,{ useEffect, useState } from 'react'
import Pricing from '../components/pricing-page/components'
import About from '../components/about/components'
import Global from '../components/global/components'
import {  graphql } from 'gatsby'
import { useDynamicImage } from '../hooks/useImage'
import { IGatsbyImageData, getImage } from 'gatsby-plugin-image'
import { PricingPageImages } from '../interfaces'


interface AboutProps {
  data: PricingPageImages
}

const AboutPage:React.FC<AboutProps> = ({data}) => {

  const images = data.allImageSharp.edges
  const [isLoad,setIsLoad] = useState<boolean>(false)
  const [contentArr,setContentArr] = useState<any>([])
  const image = useDynamicImage({images,name:'music-placeholder.png'}) as IGatsbyImageData

  const makeContent = () =>{
    let tempArr = []
    
    for(let i = 0; i < 40 ;i++){
      tempArr.push({
        image:image,
        title:'Refew - O Tři Bloky Dál',
        footer:'2017',
        link:'https://www.youtube.com/watch?v=kbdilaXZAEc'
      })
    }
    setContentArr(tempArr)
  }
  
  useEffect(()=>{
    if(!isLoad){
      makeContent()  
      setIsLoad(true)
    }else{
      makeContent()
    }
  },[isLoad])
  
  return (
    <Global.Layout title='About' className='about' meta={[]}>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      <main>
      <div className="about__introduce-section">
        <About.Introduce 
            image={useDynamicImage({images,name:'profile-pic.jpg'}) as IGatsbyImageData}
            content="My name is Miroslav Stolfa, but most of the people know me under my artistic name Fosco Alma. I am a music composer and producer, rapper, songwriter, sound engineer, programmer, but most importantly - a music lover. I was born September 26, 1989 in the Czech Republic and I have been devoted to music since I was 12 years old. During my time on the music scene, I worked on many successful or interesting projects (see References). I have been doing sound engineering as long as composing music or writing texts. In 2014, I have even founded my own music label Blakkwood Records s.r.o., which has quickly became popular and gained a large number of fans in Czech republic. At some point, when the management of the company began to grow over my head, I decided to step down from the leadership and devote more attention to what I love - the music itself again. Currently, I'm partly freelancer and I help individuals with the sound of their songs, I compose beats for clients and I devote myself to my own work. During more than 15 years I have gained precious experience and it will be my pleasure to use my professional services and offer them to you. #StayTuned"
          />
      </div>
      <div className="about__count-section">
        <div className="pricing__count-group">
          <Pricing.Count text="years of experience" number={15} />
          <Pricing.Count text="realized projects" number={100} />
          <Pricing.Count text="mastered songs" number={1000} />
          <Pricing.Count text="composed beats" number={1500} />
        </div>
      </div>
      <div className="about__reference-mix-mastering-section">
        <About.ReferenceMixMastering title="Reference / <b>Mix & Mastering</b>" contentArr={contentArr} />
      </div>
      <div className="about__reference-custom-beat-section">
        <About.ReferenceCustomBeat title='Reference / <b>Custom Beats</b>' contentArr={contentArr} />
      </div>
      <div className="pricing__clients-section">
        <div className="pricing__clients">
          <Global.Title html="What do <b>my clients</b> say?" />
          <div className="pricing__clients-say">
            <Pricing.Client image={useDynamicImage({images,name:"profile-pic-1.jpg"}) as IGatsbyImageData} text='"He has always made my songs sound great. In addition, he always went forward to meet my requirements. I can only recommend."' footText='- Refew, rapper'/>
            <Pricing.Client isRight={true} image={useDynamicImage({images,name:"profile-pic-2.jpg"}) as IGatsbyImageData} text='"Thanks for your attitude. You gave me a chance to work with a real professional. Because of you I have bigger motivation to improve myself."' footText='- Albi, rapper'/>
            <Pricing.Client image={useDynamicImage({images,name:"profile-pic-3.jpg"}) as IGatsbyImageData} text='"Fosco Alma Production is trusted and verified service for all audio professionals and enthusiasts, looking for industry ready sound. All projects that we have worked on together were individually prepared and tweaked for our needs. On time delivery, great work ethics and years of pro level experience is combination, that stands out from other audio services. If you are looking for great sound, you found your place."' footText='- Overdue, DJ and studio director'/>
          </div>
        </div>
      </div>
      </main>
      
    </Global.Layout>
  )
}
export const query = graphql`
    query {
      allImageSharp {
        edges {
          node {
            id
            gatsbyImageData(placeholder: BLURRED, layout: FULL_WIDTH, formats: WEBP)
            fluid {
              originalName
            }
          }
        }
      }
    }
  `

  export default AboutPage