import React from 'react'
export default function AboutPage():JSX.Element {
  return (
    <div>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      <main>
        <h1>about</h1>
      </main>
      
    </div>
  )
}
