import React from 'react'
import Global from '../components/global/components'
import Beats from '../components/beats/components'
import { graphql } from 'gatsby'
import { PricingPageImages } from '../interfaces'
import { useDynamicImage } from '../hooks/useImage'
import { IGatsbyImageData } from 'gatsby-plugin-image'

interface CustomBeatProps {
  data: PricingPageImages
}


const CustomBeatPage:React.FC<CustomBeatProps> = ({data}) => {
  

  const images = data.allImageSharp.edges

  return (
    <Global.Layout title='Beats' className='beats' meta={[]}>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      <main>
        <Beats.Intro html="<b>Beats</b> for you"/>
        <Beats.Detail.Detail 
          image={useDynamicImage({images,name:"detail-bg.png"}) as IGatsbyImageData} 
          placeholder={useDynamicImage({images,name:"music-placeholder.png"}) as IGatsbyImageData} 
        />
      </main>
      
    </Global.Layout>
  )
}



export const query = graphql`
    query {
      allImageSharp {
        edges {
          node {
            id
            gatsbyImageData(placeholder: BLURRED, layout: FULL_WIDTH, formats: WEBP)
            fluid {
              originalName
            }
          }
        }
      }
    }
  `
export default CustomBeatPage
