import React from 'react'
import Global from '../components/global/components'
import Pricing from '../components/pricing-page/components'
import MixMastering from '../components/mix-mastering/components'
import { graphql } from 'gatsby'
import { PricingPageImages } from '../interfaces'

interface MixPageProps {
  data: PricingPageImages
}

const CustomBeat:React.FC<MixPageProps> = ({data}) => {
  const images = data.allImageSharp.edges
  return (
    <Global.Layout title="Custom-Beat" className='custom-beat'>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      <main>
        <div className="custom-beat__intro-section">
          <Global.Title html="Custom <b>Beat</b>" />
          <p>So you want your song to be unique and original? The best solution is to have a tailored beat made basically by yourself, by your requirements. Custom beat is best done by a music producer who has many years of experience and has been on the music scene for a very long time.</p>
          <p>And you're lucky, because it's me! Fill in and submit the form and I'll be back with you. The only thing that divides you from what you want and need is this blank form!</p>
        </div>
        <div className="custom-beat__info">
          <MixMastering.Info.Info title="How does it work?" />
        </div>
        <div className="custom-beat__form-write-me-section">
          <MixMastering.Form title="Write to me <b>Your idea</b>" withoutSliders={true} />
        </div>
        <div className="pricing__introduce-section">
          <Global.Title html="Let me <b>introduce</b> myself" />
          <div className="pricing__info-content">
            <Pricing.Info.Introduce images={images} />
            <Pricing.Info.Form />
          </div>
        </div>
        <div className="pricing__count-section">
        <div className="pricing__count-group">
          <Pricing.Count text="years of experience" number={15} />
          <Pricing.Count text="realized projects" number={100} />
          <Pricing.Count text="mastered songs" number={1000} />
          <Pricing.Count text="composed beats" number={1500} />
        </div>
        <div className="pricing__sing-up">
          <Global.Title html="<b>Sign up</b> and get discount" />
          <Pricing.SignUp />
        </div>
      </div>
      </main>
      
    </Global.Layout>
  )
}

export const query = graphql`
    query {
      allImageSharp {
        edges {
          node {
            id
            gatsbyImageData(placeholder: BLURRED, layout: FULL_WIDTH, formats: WEBP)
            fluid {
              originalName
            }
          }
        }
      }
    }
  `
  export default CustomBeat