import React from 'react'
import Global from '../components/global/components'
import RapChallenge from '../components/rap-challenge/components'
import { graphql } from 'gatsby'
import { PricingPageImages } from '../interfaces'
import { useDynamicImage } from '../hooks/useImage'
import { IGatsbyImageData } from 'gatsby-plugin-image'

interface MixPageProps {
  data:PricingPageImages
}

const RapChallengePage:React.FC<MixPageProps> = ({data}) => {
  const images = data.allImageSharp.edges
  return (
    <Global.Layout title="Rap-Challenge" className='rap-challenge'>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      <main>
        <div className="rap-challenge__intro-section">
          <div className="rap-challenge__intro">
            <Global.Title html="Rap <b>Challenge</b> #3" />
            <p>Nebojíš se soutěží? Chceš ostatním ukázat co v tobě je? Nebo prostě jen miluješ hudbu? Máš možnost se realizovat! Pokud byla alespoň jedna tvoje odpověď ANO, mrkni na to, co můžeš vyhrát a jaké jsou pravidla soutěže.</p>
          </div>
        </div>
        <div className="rap-challenge__hero-section">
          <div className="rap-challenge__hero">
            <RapChallenge.HeroItem title="Výhra v hodnotě 10 000 Kč!" contentWithLink="Exkluzivní licence na <a>beat dle Tvého výběru</a> + mix a mastering" />
            <div className="rap-challenge__hero-items">
              <RapChallenge.SmallItem image={useDynamicImage({images,name:"rap-item-1.png"}) as IGatsbyImageData} foot="Streetwear" />
              <RapChallenge.SmallItem image={useDynamicImage({images,name:"rap-item-2.png"}) as IGatsbyImageData} foot="Blakkwood merchandise" />
              <RapChallenge.SmallItem image={useDynamicImage({images,name:"rap-item-3.png"}) as IGatsbyImageData} foot="Coldbrewed Ledové Čaje" />
            </div>
          </div>
        </div>
        <div className="rap-challenge__plan-section">
          <div className="rap-challenge__plan-wrapper">
            <RapChallenge.Plan 
              title="Pravidla pro soutěžící"
              one="Jde hlavně o prezentaci tvojí tvorby. Ve vlastním zájmu se snaž vytvořit co nejkvalitnější text a nahrávku,"
              two="Soutěžní song by neměl přesáhnout délku poskytnutého soutěžního beatu,"
              three="Tvůj soutěžní song ve formátu mp3 pošli na email competition@foscoalmaproduction.com a jako předmět uveď Rap Challenge #3. Samozřejmě v mailu nezapomeň uvést tvoje umělecké jméno a název songu."
              itemsTitle="Časový plán soutěže"
              planOneDate="1.12.2020"
              planOneText="Vyhlášení soutěže"
              planTwoDate="1.2.2021"
              planTwoText="Deadline pro zaslání soutěžního songu"
              planThreeDate="11.2.2021"
              planThreeText="Zveřejnění soutěžních songů  Spuštění hlasování"
              planFourDate="1.3.2021"
              planFourText="Ukončení hlasování a vyhlášení vítěze"
              foot="Zde je ke stažení <a>soutěžní beat</a>"
            />
          </div>
        </div>
        <div className="rap-challenge__profiles-section">
          <div className="rap-challenge__profiles-wrapper">
            <RapChallenge.Profiles title='Odborná porota' text='Absolutní vítěz bude vybrán odbornou porotou, která může přihlédnout k celkovým hlasům získaných jednotlivými soutěžícími.' />
          </div>
        </div>
        <div className="rap-challenge__songs-section">
          <div className="rap-challenge__songs-wrapper">
            <RapChallenge.Songs />
          </div>
        </div>
      </main>
      
    </Global.Layout>
  )
}

export const query = graphql`
    query {
      allImageSharp {
        edges {
          node {
            id
            gatsbyImageData(placeholder:BLURRED, layout:FULL_WIDTH, formats:WEBP)
            fluid {
              originalName
            }
          }
        }
      }
    }
  `
  export default RapChallengePage